apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hellotestdocker
spec:
  template:
    metadata:
      labels:
        app: hellotestdocker
    spec:
      containers:
      - name: hellotestdocker
        image: prakashg84/test:hellotestdocker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080